### ISSUE TITLE
Bounding box calculation

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/cu2qu#190]
Using cu2qu through [otf2ttf](https://github.com/adobe-type-tools/afdko/blob/develop/python/afdko/otf2ttf.py) on a number of OTFs doesn't give perfect results in some cases. It appears to happen most when curves do not have points on extremum. In the attached fonts the C and o are clear examples. Advanced width appears to be fine, but the bounding box is off. 

A visual diff:
![cu2qu_diff](https://user-images.githubusercontent.com/11257204/78408327-ad986000-75bb-11ea-8a41-c8521f0309eb.jpg)
 
[AFa724a4c6ad991aa.zip](https://github.com/googlefonts/cu2qu/files/4430014/AFa724a4c6ad991aa.zip)

**Comment by behdad** [comment]
The glyph seems shifted. Did you mean to say LSB issue, not bounding box?

I don't see how this is cu2qu issue.

**Comment by punchcutter** [comment]
No, I don't mean LSB because that doesn't change. Here's the before/after from "C":
<img width="304" alt="boundingbox" src="https://user-images.githubusercontent.com/11257204/78414873-2eaf2180-75d3-11ea-9b68-46ff63c8d403.png">

**Comment by behdad** [comment]
I'm guessing that the `otf2ttf` script is calculating `hmtx` `LSB` wrong.  Maybe it sets it to the control-box X-min of the cubic glyph, not the quadratic?  That would explain the kind of shift you are seeing.

**Comment by behdad** [comment]
Yeah that makes sense. If there's no extrema points on X/Y axes, then LSB/TSB will be different for quadratic glyph, so the hmtx/vmtx LSB/TSB need to be updated to match, or glyph will show shifted rendering.

**Comment by punchcutter** [comment]
Yeah, that totally makes sense. There's no explicit handling of hmtx or LSB which I assume is because it worked fine in most cases and nobody noticed until now. This whole process did reveal some relatively minor yet less than ideal `cu2qu` conversions in some spots, but that's unrelated to this so I'll open another issue for that.

**Comment by behdad** [comment]
Thanks.  Feel free to mention me.  I'm not watching the project.
